GET http://localhost:3000/books

###

POST http://localhost:3000/books
content-type: application/json

{
    "name": "book1",
    "price": 123
}

###
DELETE http://localhost:3000/books/5e1596ac2527d22850c19dd8